// Generated by CoffeeScript 1.8.0
(function() {
  var getStopStatusForBus, parseBusData, printMSVStatus, stringifyMVJ,
    __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  stringifyMVJ = function(j) {
    var mvj, recordedAt, s;
    mvj = j.MonitoredVehicleJourney;
    recordedAt = moment(j.recordedAtTime);
    s = "<div class='busJourney'>\n	<div class='RecordedAtTime'>Checked: " + (recordedAt.fromNow()) + "</div>\n	<div class='PublishedLineName'>" + mvj.PublishedLineName + "</div>\n	<div class='PresentableDistance'>" + mvj.MonitoredCall.Extensions.Distances.PresentableDistance + "</div>\n	<div class=\"DistanceFromCall\">" + mvj.MonitoredCall.Extensions.Distances.DistanceFromCall + "</div>\n	<div class=\"StopsFromCall\">" + mvj.MonitoredCall.Extensions.Distances.StopsFromCall + "</div>\n</div>";
    return s;
  };

  printMSVStatus = function(msv) {
    console.log(msv);
    console.log(msv.RecordedAtTime);
    console.log(msv.MonitoredVehicleJourney.MonitoredCall.Extensions.Distances);
    return $('<div />').html(stringifyMVJ(msv)).appendTo('.container');
  };

  parseBusData = function(data) {
    var dirmvjs, mvjs;
    mvjs = data['Siri']['ServiceDelivery']['VehicleMonitoringDelivery'][0]['VehicleActivity'];
    dirmvjs = _.filter(mvjs, function(d) {
      return d['MonitoredVehicleJourney']['DirectionRef'] === 1;
    });
    console.log(dirmvjs);
    _.map(dirmvjs, function(d) {
      $('<div />').html(stringifyMVJ(d)).appendTo('.container');
    });
  };

  getStopStatusForBus = function(STOP_ID, BUSNAMES) {
    $.ajax({
      url: 'http://bustime.mta.info/api/where/stop/MTA_' + STOP_ID + '.json?key=fec58d1a-9633-4366-9b43-6ed1d369c4f7',
      jsonp: 'callback',
      dataType: 'jsonp',
      success: function(data) {
        console.log(data);
        return console.log(data.data.name);
      }
    });
    $.ajax({
      url: 'http://bustime.mta.info/api/siri/stop-monitoring.json?key=fec58d1a-9633-4366-9b43-6ed1d369c4f7&OperatorRef=MTA&MonitoringRef=' + STOP_ID,
      jsonp: 'callback',
      dataType: 'jsonp',
      success: function(data) {
        _.each(data.Siri.ServiceDelivery.StopMonitoringDelivery[0].MonitoredStopVisit, function(msv) {
          var _ref;
          if (_ref = msv.MonitoredVehicleJourney.PublishedLineName, __indexOf.call(BUSNAMES, _ref) >= 0) {
            return printMSVStatus(msv);
          }
        });
      }
    });
  };

  $(document).ready(function() {
    var B57, MTA_304713, busStops;
    B57 = 'http://api.prod.obanyc.com/api/siri/vehicle-monitoring.json?key=fec58d1a-9633-4366-9b43-6ed1d369c4f7&LineRef=MTA%20NYCT_B57';
    MTA_304713 = 'http://bustime.mta.info/api/siri/stop-monitoring.xml?key=fec58d1a-9633-4366-9b43-6ed1d369c4f7&OperatorRef=MTA&MonitoringRef=304713';
    busStops = getStopStatusForBus('303813', ['B57', 'B62']);
  });

}).call(this);
