stringifyMVJ = (j) ->
	mvj = j.MonitoredVehicleJourney
	recordedAt = moment(j.recordedAtTime)
	s = """
	<div class='busJourney'>
		<div class='RecordedAtTime'>Checked: #{ recordedAt.fromNow() }</div>
		<div class='PublishedLineName'>#{ mvj.PublishedLineName }</div>
		<div class='PresentableDistance'>#{ mvj.MonitoredCall.Extensions.Distances.PresentableDistance }</div>
		<div class="DistanceFromCall">#{ mvj.MonitoredCall.Extensions.Distances.DistanceFromCall }</div>
		<div class="StopsFromCall">#{ mvj.MonitoredCall.Extensions.Distances.StopsFromCall }</div>
	</div>
	"""
	return s

printMSVStatus = (msv) ->

	console.log msv
	console.log msv.RecordedAtTime
	console.log msv.MonitoredVehicleJourney.MonitoredCall.Extensions.Distances
	$('<div />').html(stringifyMVJ(msv)).appendTo '.container'

parseBusData = (data) ->
	mvjs = data['Siri']['ServiceDelivery']['VehicleMonitoringDelivery'][0]['VehicleActivity']
	dirmvjs = _.filter(mvjs, (d) ->
		d['MonitoredVehicleJourney']['DirectionRef'] == 1
	)
	console.log dirmvjs
	_.map dirmvjs, (d) ->
		$('<div />').html(stringifyMVJ(d)).appendTo '.container'
		return
	return

getStopStatusForBus = (STOP_ID, BUSNAMES) ->

	$.ajax
		url: 'http://bustime.mta.info/api/where/stop/MTA_' + STOP_ID + '.json?key=fec58d1a-9633-4366-9b43-6ed1d369c4f7',
		jsonp: 'callback'
		dataType: 'jsonp'
		success: (data) ->
			console.log data
			console.log data.data.name

	$.ajax
		url: 'http://bustime.mta.info/api/siri/stop-monitoring.json?key=fec58d1a-9633-4366-9b43-6ed1d369c4f7&OperatorRef=MTA&MonitoringRef=' + STOP_ID,
		jsonp: 'callback'
		dataType: 'jsonp'
		success: (data) ->
			_.each data.Siri.ServiceDelivery.StopMonitoringDelivery[0].MonitoredStopVisit, (msv) ->
				if msv.MonitoredVehicleJourney.PublishedLineName in BUSNAMES
					printMSVStatus msv 
			return
	return

$(document).ready ->
	B57 = 'http://api.prod.obanyc.com/api/siri/vehicle-monitoring.json?key=fec58d1a-9633-4366-9b43-6ed1d369c4f7&LineRef=MTA%20NYCT_B57'
	MTA_304713 = 'http://bustime.mta.info/api/siri/stop-monitoring.xml?key=fec58d1a-9633-4366-9b43-6ed1d369c4f7&OperatorRef=MTA&MonitoringRef=304713'
	busStops = getStopStatusForBus('303813', ['B57', 'B62'])
#	busStops = getStopStatusForBus('304713', 'B57')
	return

# ---
# generated by js2coffee 2.0.1
